#
# Copyright 2017 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-deltalake-py
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "gcr.io/mapr-252711/apache-spark-py-3.1.2:202109242011C"
  imagePullPolicy: Always
  imagePullSecrets:
    - imagepull
  mainApplicationFile: "s3a://jobs/delta.py"
  sparkVersion: "3.1.2"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.2
    # Note: If you run app in tenant namespace - change serviceAccount name to "hpe-<namespace>"
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.2
  arguments:
    - s3a://test/tmp/test1
  sparkConf:
    "spark.hadoop.fs.s3a.endpoint": #minio endpoint
    "spark.hadoop.fs.s3a.access.key": #minio access key
    "spark.hadoop.fs.s3a.secret.key": #minio secret key
    "spark.hadoop.fs.s3a.impl": org.apache.hadoop.fs.s3a.S3AFileSystem
    "spark.sql.extensions": io.delta.sql.DeltaSparkSessionExtension
    "spark.sql.catalog.spark_catalog": org.apache.spark.sql.delta.catalog.DeltaCatalog
  deps:
    jars:
      - local:///tmp/delta-core_2.12-1.0.0.jar
