{{- if .Values.serviceAccounts.spark.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spark.serviceAccountName" . }}
  namespace: {{ include "spark-operator.sparknamespace" . }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels:
  {{- include "spark-operator.labels" . | nindent 4 }}
  {{- end }}
