kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.webhook.name }}
  namespace: {{ include "spark-operator.sparknamespace" . }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
spec:
  ports:
  - port: {{ .Values.webhook.port }}
    targetPort: {{ .Values.webhook.targetPort }}
    name: webhook
  selector:
  {{- include "spark-operator.labels" . | nindent 4 }}
